if(NOT DEFINED ZOM_BINARY_DIR OR NOT DEFINED ZOM_SOURCE_ROOT OR NOT DEFINED ZOM_TEST_PREFIX OR
   NOT DEFINED ZOMC_FILE_NAME OR NOT DEFINED ZOM_CONSUMER_MANIFEST)
  message(FATAL_ERROR "Installed core consumer test inputs are incomplete")
endif()

set(ZOM_LONG_PREFIX_COMPONENT "core-library-install-consumer-path-regression")
set(ZOM_TEST_PREFIX
    "${ZOM_TEST_PREFIX}/${ZOM_LONG_PREFIX_COMPONENT}/${ZOM_LONG_PREFIX_COMPONENT}/${ZOM_LONG_PREFIX_COMPONENT}/${ZOM_LONG_PREFIX_COMPONENT}")

file(REMOVE_RECURSE "${ZOM_TEST_PREFIX}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" --install "${ZOM_BINARY_DIR}" --prefix "${ZOM_TEST_PREFIX}"
  RESULT_VARIABLE ZOM_INSTALL_RESULT
  OUTPUT_VARIABLE ZOM_INSTALL_OUTPUT
  ERROR_VARIABLE ZOM_INSTALL_ERROR)
if(NOT ZOM_INSTALL_RESULT EQUAL 0)
  message(FATAL_ERROR "Installing the consumer distribution failed:\n${ZOM_INSTALL_OUTPUT}${ZOM_INSTALL_ERROR}")
endif()

set(ZOM_INSTALLED_COMPILER "${ZOM_TEST_PREFIX}/bin/${ZOMC_FILE_NAME}")
set(ZOM_INSTALLED_CORE "${ZOM_TEST_PREFIX}/share/zom/core/src/core.zom")
if(NOT EXISTS "${ZOM_INSTALLED_COMPILER}" OR NOT EXISTS "${ZOM_INSTALLED_CORE}")
  message(FATAL_ERROR "Installed consumer prerequisites are missing")
endif()

set(ZOM_INSTALLED_CORE_ROOT "${ZOM_TEST_PREFIX}/share/zom/core/src")
file(
  GLOB_RECURSE ZOM_INSTALLED_CORE_FILES
  LIST_DIRECTORIES false
  RELATIVE "${ZOM_INSTALLED_CORE_ROOT}"
  "${ZOM_INSTALLED_CORE_ROOT}/*")
list(SORT ZOM_INSTALLED_CORE_FILES)
set(
  ZOM_EXPECTED_CORE_FILES
  "core.zom"
  "core/marker.zom"
  "core/prelude.zom")
list(SORT ZOM_EXPECTED_CORE_FILES)
if(NOT ZOM_INSTALLED_CORE_FILES STREQUAL ZOM_EXPECTED_CORE_FILES)
  message(FATAL_ERROR "Installed core source file set differs: ${ZOM_INSTALLED_CORE_FILES}")
endif()
foreach(ZOM_CORE_FILE IN LISTS ZOM_EXPECTED_CORE_FILES)
  set(ZOM_INSTALLED_CORE_FILE "${ZOM_INSTALLED_CORE_ROOT}/${ZOM_CORE_FILE}")
  set(ZOM_SOURCE_CORE_FILE "${ZOM_SOURCE_ROOT}/core/src/${ZOM_CORE_FILE}")
  if(IS_SYMLINK "${ZOM_INSTALLED_CORE_FILE}")
    message(FATAL_ERROR "Installed core source must not be a symlink: ${ZOM_CORE_FILE}")
  endif()
  file(SHA256 "${ZOM_INSTALLED_CORE_FILE}" ZOM_INSTALLED_CORE_DIGEST)
  file(SHA256 "${ZOM_SOURCE_CORE_FILE}" ZOM_SOURCE_CORE_DIGEST)
  if(NOT ZOM_INSTALLED_CORE_DIGEST STREQUAL ZOM_SOURCE_CORE_DIGEST)
    message(FATAL_ERROR "Installed core source bytes differ: ${ZOM_CORE_FILE}")
  endif()
endforeach()

set(ZOM_DIRECT_WORK_DIRECTORY "${ZOM_TEST_PREFIX}/direct-invocation")
file(MAKE_DIRECTORY "${ZOM_DIRECT_WORK_DIRECTORY}")
execute_process(
  COMMAND "${ZOM_INSTALLED_COMPILER}" compile --manifest-path "${ZOM_CONSUMER_MANIFEST}"
          --package installed_consumer --bin installed_consumer --check
  WORKING_DIRECTORY "${ZOM_DIRECT_WORK_DIRECTORY}"
  RESULT_VARIABLE ZOM_CONSUMER_RESULT
  OUTPUT_VARIABLE ZOM_CONSUMER_OUTPUT
  ERROR_VARIABLE ZOM_CONSUMER_ERROR)
if(NOT ZOM_CONSUMER_RESULT EQUAL 0)
  message(FATAL_ERROR "Installed consumer compilation failed:\n${ZOM_CONSUMER_OUTPUT}${ZOM_CONSUMER_ERROR}")
endif()
if(NOT ZOM_CONSUMER_OUTPUT STREQUAL "" OR NOT ZOM_CONSUMER_ERROR STREQUAL "")
  message(FATAL_ERROR "Installed consumer check was not silent:\n${ZOM_CONSUMER_OUTPUT}${ZOM_CONSUMER_ERROR}")
endif()
file(GLOB ZOM_DIRECT_CONSUMER_ARTIFACTS "${ZOM_DIRECT_WORK_DIRECTORY}/*")
if(ZOM_DIRECT_CONSUMER_ARTIFACTS)
  message(FATAL_ERROR "Direct installed consumer check emitted artifacts")
endif()

set(ZOM_PATH_WORK_DIRECTORY "${ZOM_TEST_PREFIX}/path-invocation")
file(MAKE_DIRECTORY "${ZOM_PATH_WORK_DIRECTORY}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "PATH=${ZOM_TEST_PREFIX}/bin:$ENV{PATH}"
          "${ZOMC_FILE_NAME}" compile --manifest-path "${ZOM_CONSUMER_MANIFEST}"
          --package installed_consumer --bin installed_consumer --check
  WORKING_DIRECTORY "${ZOM_PATH_WORK_DIRECTORY}"
  RESULT_VARIABLE ZOM_PATH_CONSUMER_RESULT
  OUTPUT_VARIABLE ZOM_PATH_CONSUMER_OUTPUT
  ERROR_VARIABLE ZOM_PATH_CONSUMER_ERROR)
if(NOT ZOM_PATH_CONSUMER_RESULT EQUAL 0)
  message(FATAL_ERROR "PATH-installed consumer compilation failed:\n${ZOM_PATH_CONSUMER_OUTPUT}${ZOM_PATH_CONSUMER_ERROR}")
endif()
if(NOT ZOM_PATH_CONSUMER_OUTPUT STREQUAL "" OR NOT ZOM_PATH_CONSUMER_ERROR STREQUAL "")
  message(FATAL_ERROR "PATH-installed consumer check was not silent:\n${ZOM_PATH_CONSUMER_OUTPUT}${ZOM_PATH_CONSUMER_ERROR}")
endif()
file(GLOB ZOM_PATH_CONSUMER_ARTIFACTS "${ZOM_PATH_WORK_DIRECTORY}/*")
if(ZOM_PATH_CONSUMER_ARTIFACTS)
  message(FATAL_ERROR "PATH-installed consumer check emitted artifacts")
endif()

set(ZOM_SYMLINK_BIN_DIRECTORY "${ZOM_TEST_PREFIX}/symlink-bin")
file(MAKE_DIRECTORY "${ZOM_SYMLINK_BIN_DIRECTORY}")
set(ZOM_SYMLINK_COMPILER "${ZOM_SYMLINK_BIN_DIRECTORY}/${ZOMC_FILE_NAME}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E create_symlink "${ZOM_INSTALLED_COMPILER}" "${ZOM_SYMLINK_COMPILER}"
  RESULT_VARIABLE ZOM_SYMLINK_RESULT
  OUTPUT_VARIABLE ZOM_SYMLINK_OUTPUT
  ERROR_VARIABLE ZOM_SYMLINK_ERROR)
if(NOT ZOM_SYMLINK_RESULT EQUAL 0)
  message(FATAL_ERROR "Creating the installed compiler symlink failed:\n${ZOM_SYMLINK_OUTPUT}${ZOM_SYMLINK_ERROR}")
endif()
set(ZOM_SYMLINK_WORK_DIRECTORY "${ZOM_TEST_PREFIX}/symlink-invocation")
file(MAKE_DIRECTORY "${ZOM_SYMLINK_WORK_DIRECTORY}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "PATH=${ZOM_SYMLINK_BIN_DIRECTORY}:$ENV{PATH}"
          "${ZOMC_FILE_NAME}" compile --manifest-path "${ZOM_CONSUMER_MANIFEST}"
          --package installed_consumer --bin installed_consumer --check
  WORKING_DIRECTORY "${ZOM_SYMLINK_WORK_DIRECTORY}"
  RESULT_VARIABLE ZOM_SYMLINK_CONSUMER_RESULT
  OUTPUT_VARIABLE ZOM_SYMLINK_CONSUMER_OUTPUT
  ERROR_VARIABLE ZOM_SYMLINK_CONSUMER_ERROR)
if(NOT ZOM_SYMLINK_CONSUMER_RESULT EQUAL 0)
  message(FATAL_ERROR "Symlink-installed consumer compilation failed:\n${ZOM_SYMLINK_CONSUMER_OUTPUT}${ZOM_SYMLINK_CONSUMER_ERROR}")
endif()
if(NOT ZOM_SYMLINK_CONSUMER_OUTPUT STREQUAL "" OR NOT ZOM_SYMLINK_CONSUMER_ERROR STREQUAL "")
  message(FATAL_ERROR "Symlink-installed consumer check was not silent:\n${ZOM_SYMLINK_CONSUMER_OUTPUT}${ZOM_SYMLINK_CONSUMER_ERROR}")
endif()
file(GLOB ZOM_SYMLINK_CONSUMER_ARTIFACTS "${ZOM_SYMLINK_WORK_DIRECTORY}/*")
if(ZOM_SYMLINK_CONSUMER_ARTIFACTS)
  message(FATAL_ERROR "Symlink-installed consumer check emitted artifacts")
endif()

file(REMOVE_RECURSE "${ZOM_TEST_PREFIX}")
