#!/usr/bin/env python3

"""Generate the source-backed core-library inventory embedded by zomc."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE_ROOT = ROOT / "core/src"
REQUIRED_FILES = (
    Path("core.zom"),
    Path("core/marker.zom"),
    Path("core/prelude.zom"),
)
REQUIRED_CONTENT = {
    Path("core.zom"): b"module core;\n",
    Path("core/marker.zom"): b"module marker;\n\nexport interface Copy {}\nexport interface Linear {}\n",
    Path("core/prelude.zom"): b"module prelude;\n\nexport core::marker::{Copy, Linear};\n",
}
RECORD_DOMAIN = b"zom.core-distribution"


class InventoryError(ValueError):
    pass


def encode_u32(value: int) -> bytes:
    return value.to_bytes(4, byteorder="big", signed=False)


def encode_u64(value: int) -> bytes:
    return value.to_bytes(8, byteorder="big", signed=False)


def encode_text(value: str) -> bytes:
    encoded = value.encode("ascii")
    return encode_u64(len(encoded)) + encoded


def encode_path(path: Path) -> bytes:
    parts = path.parts
    return encode_u64(len(parts)) + b"".join(encode_text(part) for part in parts)


def require_canonical_source(path: Path, expected: bytes) -> bytes:
    if not path.exists():
        raise InventoryError(f"missing required source: {path}")
    if path.is_symlink():
        raise InventoryError(f"source must not be a symlink: {path}")
    if not path.is_file():
        raise InventoryError(f"source must be a regular file: {path}")
    value = path.read_bytes()
    try:
        value.decode("utf-8")
    except UnicodeDecodeError as error:
        raise InventoryError(f"source is not valid UTF-8: {path}") from error
    if b"\r" in value:
        raise InventoryError(f"source must use LF line endings: {path}")
    if any(line.endswith((b" ", b"\t")) for line in value.splitlines()):
        raise InventoryError(f"source contains trailing whitespace: {path}")
    if value != expected:
        raise InventoryError(f"source does not match the accepted core declaration: {path}")
    return value


def load_inventory(source_root: Path) -> tuple[tuple[Path, bytes], ...]:
    if source_root.is_symlink() or not source_root.is_dir():
        raise InventoryError(f"source root must be a regular directory: {source_root}")
    entries: list[tuple[Path, bytes]] = []
    seen: set[Path] = set()
    for path in sorted(source_root.rglob("*")):
        relative = path.relative_to(source_root)
        if path.is_symlink():
            raise InventoryError(f"source tree must not contain symlinks: {relative}")
        if path.is_dir():
            continue
        if not path.is_file():
            raise InventoryError(f"source tree contains a non-regular entry: {relative}")
        if relative not in REQUIRED_CONTENT:
            raise InventoryError(f"source tree contains an additional file: {relative}")
        entries.append((relative, require_canonical_source(path, REQUIRED_CONTENT[relative])))
        seen.add(relative)
    missing = set(REQUIRED_FILES) - seen
    if missing:
        raise InventoryError(f"source tree is missing required files: {', '.join(map(str, sorted(missing)))}")
    return tuple(entries)


def encode_role(tag: int, name: str) -> bytes:
    return (
        bytes((tag,))
        + encode_u64(2)
        + encode_text("core")
        + encode_text("marker")
        + encode_u64(0)
        + bytes((0x08, 0x02))
        + encode_text(name)
        + bytes((0x00,))
    )


def encode_record(entries: tuple[tuple[Path, bytes], ...]) -> bytes:
    digests = {path: hashlib.sha256(value).digest() for path, value in entries}
    record = bytearray()
    record.extend(encode_u32(2026))
    record.extend(encode_path(Path("core.zom")))
    record.extend(encode_path(Path("core/prelude.zom")))
    record.extend(encode_u64(len(REQUIRED_FILES)))
    for path in REQUIRED_FILES:
        record.extend(encode_path(path))
        record.extend(digests[path])
    record.extend(encode_u64(2))
    record.extend(encode_role(0x01, "Copy"))
    record.extend(encode_role(0x02, "Linear"))
    return bytes(record)


def generated_content(record: bytes) -> bytes:
    digest = hashlib.sha256(RECORD_DOMAIN + b"\0" + record).digest()

    def format_bytes(value: bytes) -> str:
        rows = [value[index : index + 12] for index in range(0, len(value), 12)]
        return "\n".join(
            "    " + ", ".join(f"0x{byte:02x}" for byte in row) + "," for row in rows
        )

    return (
        "// Generated by scripts/codegen/gen_core_library_inventory.py. DO NOT EDIT.\n"
        "constexpr uint8_t kGeneratedCoreDistributionRecord[] = {\n"
        f"{format_bytes(record)}\n"
        "};\n\n"
        "constexpr uint8_t kGeneratedCoreDistributionDigest[] = {\n"
        f"{format_bytes(digest)}\n"
        "};\n"
    ).encode("ascii")


def atomic_write(path: Path, value: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_bytes(value)
    os.replace(temporary, path)


def require_current_generated(path: Path, expected: bytes) -> None:
    if not path.is_file() or path.read_bytes() != expected:
        raise InventoryError(f"generated inventory is stale: {path}")


def self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="zom-core-inventory-") as temporary_directory:
        root = Path(temporary_directory) / "src"
        for relative, value in REQUIRED_CONTENT.items():
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(value)
        baseline = generated_content(encode_record(load_inventory(root)))
        if baseline != generated_content(encode_record(load_inventory(root))):
            raise InventoryError("generator output is not deterministic")

        fixtures = (
            "missing required file",
            "additional file",
            "non-canonical path",
            "symlink",
            "invalid UTF-8",
            "CRLF",
            "trailing whitespace",
        )
        failures: list[str] = []
        for name in fixtures:
            fixture_root = Path(tempfile.mkdtemp(prefix="zom-core-inventory-fixture-")) / "src"
            shutil.copytree(root, fixture_root)
            mutation_root = fixture_root
            try:
                if name == "missing required file":
                    (mutation_root / "core.zom").unlink()
                elif name == "additional file":
                    (mutation_root / "unexpected.zom").write_text("module unexpected;\n")
                elif name == "non-canonical path":
                    (mutation_root / "core/mod.zom").write_text("module core;\n")
                elif name == "symlink":
                    (mutation_root / "core/link.zom").symlink_to(mutation_root / "core.zom")
                elif name == "invalid UTF-8":
                    (mutation_root / "core.zom").write_bytes(b"\xff")
                elif name == "CRLF":
                    (mutation_root / "core.zom").write_bytes(b"module core;\r\n")
                else:
                    (mutation_root / "core.zom").write_bytes(b"module core; \n")
                try:
                    load_inventory(mutation_root)
                except InventoryError:
                    continue
                failures.append(name)
            finally:
                shutil.rmtree(fixture_root.parent)
        framing_mutation = bytearray(baseline)
        framing_mutation[len(framing_mutation) // 2] ^= 0x01
        generated = root.parent / "core-library-inventory.inc"
        generated.write_bytes(bytes(framing_mutation))
        try:
            require_current_generated(generated, baseline)
        except InventoryError:
            pass
        else:
            failures.append("framing mutation")
        if failures:
            raise InventoryError("self-test did not reject: " + ", ".join(failures))
    print("core library inventory self-test passed (8/8)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the fixed core-library inventory")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="validate the fixed source inventory")
    mode.add_argument("--self-test", action="store_true", help="run mutation coverage")
    parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT)
    parser.add_argument("--output", type=Path)
    arguments = parser.parse_args()
    try:
        if arguments.self_test:
            self_test()
            return 0
        entries = load_inventory(arguments.source_root)
        content = generated_content(encode_record(entries))
        if arguments.check:
            if arguments.output is not None:
                require_current_generated(arguments.output, content)
            print("core library inventory check passed")
            return 0
        if arguments.output is None:
            parser.error("--output is required when generating")
        atomic_write(arguments.output, content)
        print("core library inventory generated")
        return 0
    except (OSError, InventoryError) as error:
        print(f"core library inventory failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
