#!/usr/bin/env python3
"""Generate ZOM AST schema support files.

The schema input is products/zomlang/compiler/ast/schema.yml by default. The
generated files are intentionally small integration headers for the main
zomlang::compiler::ast namespace; the C++ implementation owns storage and tree
mutation behavior.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from typing import Any

import yaml


REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
DEFAULT_SCHEMA = os.path.join(REPO_ROOT, "products", "zomlang", "compiler", "ast", "schema.yml")
DEFAULT_OUTPUT_DIR = os.path.join(
    REPO_ROOT, "products", "zomlang", "compiler", "ast", "generated"
)
NAMESPACE_OPEN = "namespace zomlang {\nnamespace compiler {\nnamespace ast {"
NAMESPACE_CLOSE = "}  // namespace ast\n}  // namespace compiler\n}  // namespace zomlang"
HEADER = """// Copyright (c) 2024-2025 Zode.Z. All rights reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// Auto-generated by scripts/codegen/gen_ast.py. Do not edit by hand.
// clang-format off
#pragma once
"""


class SchemaError(RuntimeError):
    pass


def load_schema(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as handle:
        value = yaml.safe_load(handle)
    if not isinstance(value, dict):
        raise SchemaError("schema root must be a mapping")
    return value


def as_int(value: Any) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        return int(value, 0)
    raise SchemaError(f"integer value expected, got {value!r}")


def variants(schema: dict[str, Any]) -> list[dict[str, Any]]:
    raw = schema.get("variants")
    if not isinstance(raw, list):
        raise SchemaError("schema.variants must be a list")
    result: list[dict[str, Any]] = []
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise SchemaError(f"variant {index} must be a mapping")
        if "id" not in item or "name" not in item:
            raise SchemaError(f"variant {index} must define id and name")
        result.append(item)
    return sorted(result, key=lambda item: as_int(item["id"]))


def categories(schema: dict[str, Any]) -> dict[str, tuple[int, int]]:
    raw = schema.get("categories")
    if not isinstance(raw, dict):
        raise SchemaError("schema.categories must be a mapping")
    result: dict[str, tuple[int, int]] = {}
    for name, item in raw.items():
        if not isinstance(item, dict):
            raise SchemaError(f"category {name} must be a mapping")
        result[name] = (as_int(item["first"]), as_int(item["last"]))
    return result


def field_types(schema: dict[str, Any]) -> set[str]:
    raw = schema.get("field_type_mapping")
    if not isinstance(raw, dict):
        raise SchemaError("schema.field_type_mapping must be a mapping")
    enum_names = set(schema.get("enums", {}).keys())
    return set(raw.keys()) | enum_names


def variant_fields(item: dict[str, Any]) -> list[dict[str, Any]]:
    fields = item.get("fields", [])
    if fields is None:
        return []
    if not isinstance(fields, list):
        raise SchemaError(f"{item.get('name', '<unnamed>')}.fields must be a list")
    return [field for field in fields if isinstance(field, dict)]


def field_word_count(field_type: str) -> int:
    if field_type in {"NodeList", "IdentList", "uint64"}:
        return 2
    return 1


def field_name_fragment(name: str) -> str:
    stripped = name.rstrip("_")
    parts = [part for part in stripped.split("_") if part]
    if not parts:
        raise SchemaError(f"field name cannot be converted to a constant fragment: {name!r}")
    return "".join(part[:1].upper() + part[1:] for part in parts)


def payload_layout(item: dict[str, Any]) -> tuple[list[tuple[dict[str, Any], int, int]], int]:
    layout: list[tuple[dict[str, Any], int, int]] = []
    word = 0
    for field in variant_fields(item):
        count = field_word_count(str(field["type"]))
        layout.append((field, word, count))
        word += count
    return layout, word


def validate_payload_layouts(schema: dict[str, Any]) -> None:
    for item in variants(schema):
        _, word_count = payload_layout(item)
        if word_count > 6:
            raise SchemaError(f"{item['name']} payload uses {word_count} words; max is 6")


def validate_schema(schema: dict[str, Any]) -> None:
    node_variants = variants(schema)
    ids: dict[int, str] = {}
    names: dict[str, int] = {}
    for item in node_variants:
        node_id = as_int(item["id"])
        name = str(item["name"])
        if node_id in ids:
            raise SchemaError(f"duplicate node id {node_id:#x}: {ids[node_id]} and {name}")
        if name in names:
            raise SchemaError(f"duplicate node name {name}")
        ids[node_id] = name
        names[name] = node_id

    ranges = categories(schema)
    ordered_ranges = list(ranges.items())
    for index, (left_name, (left_first, left_last)) in enumerate(ordered_ranges):
        if left_first > left_last:
            raise SchemaError(f"category {left_name} has an inverted range")
        for right_name, (right_first, right_last) in ordered_ranges[index + 1:]:
            if left_first <= right_last and right_first <= left_last:
                raise SchemaError(f"category ranges overlap: {left_name} and {right_name}")

    allowed_types = field_types(schema)
    allowed_casts = set(names) | set(ranges) | set(schema.get("union_predicates", []))
    for item in node_variants:
        name = str(item["name"])
        for field in variant_fields(item):
            field_name = str(field.get("name", "<unnamed>"))
            field_type = str(field.get("type", ""))
            if field_type not in allowed_types:
                raise SchemaError(f"{name}.{field_name} uses unknown field type {field_type}")
            cast_target = field.get("cast")
            if cast_target is not None and str(cast_target) not in allowed_casts:
                raise SchemaError(f"{name}.{field_name} uses unknown cast target {cast_target}")
    validate_payload_layouts(schema)


def schema_fingerprint(schema: dict[str, Any]) -> str:
    payload = {
        "version": schema.get("version"),
        "categories": schema.get("categories", {}),
        "variants": [
            {
                "id": as_int(item["id"]),
                "name": item["name"],
                "fields": [field for field in item.get("fields", []) if isinstance(field, dict)],
            }
            for item in variants(schema)
        ],
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def generated_notice(schema: dict[str, Any]) -> str:
    return f"// Schema version: {schema.get('version', 'unknown')}\n"


def generate_node_kind_inc(schema: dict[str, Any]) -> str:
    lines = [
        "// Auto-generated by scripts/codegen/gen_ast.py. Do not edit by hand.",
        "// Include with ZOM_AST_NODE(name, value) defined.",
        "",
    ]
    for item in variants(schema):
        lines.append(f"ZOM_AST_NODE({item['name']}, {as_int(item['id']):#05x})")
    return "\n".join(lines) + "\n"


def generate_node_payload_h(schema: dict[str, Any]) -> str:
    enum_lines: list[str] = []
    raw_enums = schema.get("enums", {})
    if isinstance(raw_enums, dict):
        for enum_name, item in raw_enums.items():
            if not isinstance(item, dict):
                raise SchemaError(f"enum {enum_name} must be a mapping")
            underlying = str(item.get("type", "uint8"))
            values = item.get("values", [])
            if not isinstance(values, list):
                raise SchemaError(f"enum {enum_name}.values must be a list")
            enum_lines.append(f"enum class {enum_name} : {underlying}_t {{")
            enum_lines.append("  " + ", ".join(str(value) for value in values))
            enum_lines.append("};")
            enum_lines.append("")

    lines = [
        HEADER,
        generated_notice(schema),
        '#include <cstdint>',
        "",
        '#include "zomlang/compiler/ast/tree.h"',
        "",
        NAMESPACE_OPEN,
        "",
    ]
    lines.extend(enum_lines)
    lines += [
        "constexpr uint32_t kNodePayloadWordCount = 6;",
        "",
    ]
    for item in variants(schema):
        variant_name = str(item["name"])
        layout, word_count = payload_layout(item)
        lines.append(f"constexpr uint32_t k{variant_name}PayloadWordCount = {word_count};")
        for field, word, count in layout:
            field_name = field_name_fragment(str(field["name"]))
            field_type = str(field["type"])
            if field_type in {"NodeList", "IdentList"}:
                lines.append(f"constexpr uint32_t k{variant_name}{field_name}FirstWord = {word};")
                lines.append(
                    f"constexpr uint32_t k{variant_name}{field_name}SizeWord = {word + 1};"
                )
            elif field_type == "uint64":
                lines.append(f"constexpr uint32_t k{variant_name}{field_name}LowWord = {word};")
                lines.append(f"constexpr uint32_t k{variant_name}{field_name}HighWord = {word + 1};")
            else:
                lines.append(f"constexpr uint32_t k{variant_name}{field_name}Word = {word};")
            if count == 0:
                raise SchemaError(f"{variant_name}.{field['name']} has zero payload width")
        lines.append("")
    lines.append(NAMESPACE_CLOSE)
    return "\n".join(lines) + "\n"


def generate_node_accessors_h(schema: dict[str, Any]) -> str:
    lines = [
        HEADER,
        generated_notice(schema),
        '#include "zomlang/compiler/ast/generated/node-payload.h"',
        "",
        NAMESPACE_OPEN,
        "",
        "constexpr uint32_t payloadWord(NodeId id) noexcept { return id.value; }",
        "constexpr uint32_t payloadWord(StringId id) noexcept { return id.value; }",
        "constexpr uint32_t payloadWord(IdentId id) noexcept { return id.value; }",
        "constexpr uint32_t payloadWord(BigIntId id) noexcept { return id.value; }",
        "constexpr uint32_t payloadWord(FloatId id) noexcept { return id.value; }",
        "",
        "constexpr NodeId nodeIdFromPayload(uint32_t word) noexcept { return NodeId(word); }",
        "constexpr StringId stringIdFromPayload(uint32_t word) noexcept { return StringId(word); }",
        "constexpr IdentId identIdFromPayload(uint32_t word) noexcept { return IdentId(word); }",
        "constexpr BigIntId bigIntIdFromPayload(uint32_t word) noexcept { return BigIntId(word); }",
        "constexpr FloatId floatIdFromPayload(uint32_t word) noexcept { return FloatId(word); }",
        "",
        "constexpr NodeList nodeListFromPayload(const Node& node, uint32_t firstWord,",
        "                                       uint32_t sizeWord) noexcept {",
        "  NodeList list;",
        "  list.first = node.payload.words[firstWord];",
        "  list.size = node.payload.words[sizeWord];",
        "  return list;",
        "}",
        "",
        "constexpr IdentList identListFromPayload(const Node& node, uint32_t firstWord,",
        "                                         uint32_t sizeWord) noexcept {",
        "  IdentList list;",
        "  list.first = node.payload.words[firstWord];",
        "  list.size = node.payload.words[sizeWord];",
        "  return list;",
        "}",
        "",
        "constexpr bool isEmpty(NodeId id) noexcept { return !static_cast<bool>(id); }",
        "constexpr bool isEmpty(StringId id) noexcept { return !static_cast<bool>(id); }",
        "constexpr bool isEmpty(IdentId id) noexcept { return !static_cast<bool>(id); }",
        "constexpr bool isEmpty(BigIntId id) noexcept { return !static_cast<bool>(id); }",
        "constexpr bool isEmpty(FloatId id) noexcept { return !static_cast<bool>(id); }",
        "",
        "constexpr bool kindInRange(SyntaxKind kind, uint32_t first, uint32_t last) noexcept {",
        "  const uint32_t value = static_cast<uint32_t>(kind);",
        "  return value >= first && value <= last;",
        "}",
        "",
    ]
    for category_name, (first, last) in categories(schema).items():
        lines.append(f"constexpr bool is{category_name}Kind(SyntaxKind kind) noexcept {{")
        lines.append(f"  return kindInRange(kind, {first:#05x}, {last:#05x});")
        lines.append("}")
        lines.append("")

    lines += [
        "constexpr bool isKnownAstKind(SyntaxKind kind) noexcept {",
        "  switch (kind) {",
    ]
    for item in variants(schema):
        name = item["name"]
        lines.append(f"    case SyntaxKind::{name}: return true;")
    lines += [
        "    default: return false;",
        "  }",
        "}",
        "",
        "constexpr const char* nodeKindName(SyntaxKind kind) noexcept {",
        "  switch (kind) {",
    ]
    for item in variants(schema):
        name = item["name"]
        lines.append(f"    case SyntaxKind::{name}: return \"{name}\";")
    lines += [
        "    default: return \"Unknown\";",
        "  }",
        "}",
        "",
        NAMESPACE_CLOSE,
    ]
    return "\n".join(lines) + "\n"


def generate_node_schema_h(schema: dict[str, Any]) -> str:
    fingerprint = schema_fingerprint(schema)
    lines = [
        HEADER,
        generated_notice(schema),
        '#include <cstdint>',
        "",
        '#include "zomlang/compiler/ast/kinds.h"',
        "",
        NAMESPACE_OPEN,
        "",
        "struct NodeSchemaEntry final {",
        "  SyntaxKind kind;",
        "  const char* name;",
        "};",
        "",
        f'constexpr const char* kAstSchemaFingerprint = "{fingerprint}";',
        f"constexpr uint32_t kAstSchemaVariantCount = {len(variants(schema))};",
        "",
        NAMESPACE_CLOSE,
    ]
    return "\n".join(lines) + "\n"


def generate_node_traverse_h(schema: dict[str, Any]) -> str:
    lines = [
        HEADER,
        '#include "zomlang/compiler/ast/generated/node-payload.h"',
        '#include "zomlang/compiler/ast/tree.h"',
        "",
        NAMESPACE_OPEN,
        "",
        "template <typename Fn>",
        "void visitNode(const Node& node, Fn&& fn) {",
        "  fn(node);",
        "}",
        "",
        "template <typename Fn>",
        "void visitChildNodeIds(const Tree& tree, const Node& node, Fn&& fn) {",
        "  switch (node.kind) {",
    ]
    for item in variants(schema):
        variant_name = str(item["name"])
        child_lines: list[str] = []
        for field, _, _ in payload_layout(item)[0]:
            field_type = str(field["type"])
            field_name = field_name_fragment(str(field["name"]))
            if field_type == "NodeId":
                child_lines += [
                    "      {",
                    f"        const NodeId child(node.payload.words[k{variant_name}{field_name}Word]);",
                    "        if (tree.contains(child)) { fn(child); }",
                    "      }",
                ]
            elif field_type == "NodeList":
                child_lines += [
                    "      {",
                    "        NodeList list;",
                    f"        list.first = node.payload.words[k{variant_name}{field_name}FirstWord];",
                    f"        list.size = node.payload.words[k{variant_name}{field_name}SizeWord];",
                    "        for (NodeId child : tree.list(list)) { fn(child); }",
                    "      }",
                ]
        if child_lines:
            lines.append(f"    case SyntaxKind::{variant_name}:")
            lines.extend(child_lines)
            lines.append("      return;")

    lines += [
        "    default:",
        "      return;",
        "  }",
        "}",
        "",
        "template <typename Fn>",
        "void visitTreePreOrder(const Tree& tree, NodeId node, Fn&& fn) {",
        "  fn(node, tree.node(node));",
        "  visitChildNodeIds(tree, tree.node(node), [&](NodeId child) {",
        "    visitTreePreOrder(tree, child, fn);",
        "  });",
        "}",
        "",
        NAMESPACE_CLOSE,
    ]
    return "\n".join(lines) + "\n"


GENERATORS = {
    "node-kind.inc": generate_node_kind_inc,
    "node-payload.h": generate_node_payload_h,
    "node-accessors.h": generate_node_accessors_h,
    "node-schema.h": generate_node_schema_h,
    "node-traverse.h": generate_node_traverse_h,
}


def write_outputs(schema: dict[str, Any], output_dir: str) -> None:
    os.makedirs(output_dir, exist_ok=True)
    for filename, generator in GENERATORS.items():
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(generator(schema))
        print(f"wrote {path}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate ZOM AST schema support files")
    parser.add_argument("--schema", default=DEFAULT_SCHEMA, help="path to ast schema.yml")
    parser.add_argument(
        "--output-dir",
        "--out-dir",
        default=DEFAULT_OUTPUT_DIR,
        dest="output_dir",
        help="directory for generated files",
    )
    parser.add_argument("--check", action="store_true", help="validate schema only")
    parser.add_argument("--write", action="store_true", help="write generated files")
    args = parser.parse_args(argv)

    try:
        schema = load_schema(args.schema)
        validate_schema(schema)
    except (OSError, SchemaError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"schema ok: {len(variants(schema))} variants")
    if args.check:
        return 0
    if not args.write:
        print("no files written; pass --write to generate outputs")
        return 0
    write_outputs(schema, os.path.abspath(args.output_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
